# Generated by Django 2.2.5 on 2022-06-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgiletaskTracker', '0002_auto_20220605_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='author',
            new_name='assignee',
        ),
    ]
